version: '3.9'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    depends_on:
      - db

  frontend:
    build: ./frontend/wms-frontend
    ports:
      - "3001:3000"
    volumes:
      - ./frontend/wms-frontend:/app

  db:
    image: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: wms
      POSTGRES_USER: wmsuser
      POSTGRES_PASSWORD: wmspassword
    ports:
      - "5432:5432"

volumes:
  postgres_data:
